# From SQL to Pandas Challenge 1

In [ ]:
# import libraries
import pandas as pd

# load data
# This code is made to load our data stored on Google Drive
def gd_path(file_id):
    """Generate a shareable link from Google Drive file id."""
    return f"https://drive.google.com/uc?export=download&id={file_id}"

# Google Drive file ids
files_id = {
    "titleauthor": "1F1JOiYXStWacOBca6coNVfyVtoST7ZgD",
    "titles": "1PLdn50N9GRa53ZbuVWo0l47F_IXdvlEm",
    "sales": "1fzFc9rwYmVIPaGOFmhLVxCi3kg19vNU2",
    "publishers": "1s9E8_AVOziTrowb3wyh2jg3PV763VOyq",
    "jobs": "1V1Za8hUdXD-vJOyRdX4aQV5wanIff2eM",
    "authors": "1fEF89Nhe61EebAljKlwFwfEuokK0o6aJ"
}

# Read data from Google Drive
sales = pd.read_csv(gd_path(files_id["sales"]), sep=";")
authors = pd.read_csv(gd_path(files_id["authors"]), sep=";")
titleauthor = pd.read_csv(gd_path(files_id["titleauthor"]), sep=";")
publishers = pd.read_csv(gd_path(files_id["publishers"]), sep=";")
jobs = pd.read_csv(gd_path(files_id["jobs"]), sep=";")
titles = pd.read_csv(gd_path(files_id["titles"]), sep=";")

We have loaded the tables:

* `sales`
* `authors`
* `titleauthor`
* `publishers`
* `jobs`
* `titles`

You can use them by writing `sales`, `authors`, `titleauthor`, `publishers`, `jobs` or `titles` in a cell.

## 1.&nbsp;Select everything from the table authors

In [ ]:
authors

,au_id,au_lname,au_fname,phone,address,city,state,zip,contract
0,172-32-1176,White,Johnson,408 496-7223,10932 Bigge Rd.,Menlo Park,CA,94025,1
1,213-46-8915,Green,Marjorie,415 986-7020,309 63rd St. #411,Oakland,CA,94618,1
2,238-95-7766,Carson,Cheryl,415 548-7723,589 Darwin Ln.,Berkeley,CA,94705,1
3,267-41-2394,O'Leary,Michael,408 286-2428,22 Cleveland Av. #14,San Jose,CA,95128,1
4,274-80-9391,Straight,Dean,415 834-2919,5420 College Av.,Oakland,CA,94609,1
5,341-22-1782,Smith,Meander,913 843-0462,10 Mississippi Dr.,Lawrence,KS,66044,0
6,409-56-7008,Bennet,Abraham,415 658-9932,6223 Bateman St.,Berkeley,CA,94705,1
7,427-17-2319,Dull,Ann,415 836-7128,3410 Blonde St.,Palo Alto,CA,94301,1
8,472-27-2349,Gringlesby,Burt,707 938-6445,PO Box 792,Covelo,CA,95428,1
9,486-29-1786,Locksley,Charlene,415 585-4620,18 Broadway Av.,San Francisco,CA,94130,1
10,527-72-3246,Greene,Morningstar,615 297-2723,22 Graybar House Rd.,Nashville,TN,37215,0
11,648-92-1872,Blotchet-Halls,Reginald,503 745-6402,55 Hillsdale Bl.,Corvallis,OR,97330,1
12,672-71-3249,Yokomoto,Akiko,415 935-4228,3 Silver Ct.,Walnut Creek,CA,94595,1
13,712-45-1867,del Castillo,Innes,615 996-8275,2286 Cram Pl. #86,Ann Arbor,MI,48105,1
14,722-51-5454,DeFrance,Michel,219 547-9982,3 Balding Pl.,Gary,IN,46403,1
15,724-08-9931,Stringer,Dirk,415 843-2991,5420 Telegraph Av.,Oakland,CA,94609,0
16,724-80-9391,MacFeather,Stearns,415 354-7128,44 Upland Hts.,Oakland,CA,94612,1
17,756-30-7391,Karsen,Livia,415 534-9219,5720 McAuley St.,Oakland,CA,94609,1
18,807-91-6654,Panteley,Sylvia,301 946-8853,1956 Arlington Pl.,Rockville,MD,20853,1
19,846-92-7186,Hunter,Sheryl,415 836-7128,3410 Blonde St.,Palo Alto,CA,94301,1
20,893-72-1158,McBadden,Heather,707 448-4982,301 Putnam,Vacaville,CA,95688,0
21,899-46-2035,Ringer,Anne,801 826-0752,67 Seventh Av.,Salt Lake City,UT,84152,1
22,998-72-3567,Ringer,Albert,801 826-0752,67 Seventh Av.,Salt Lake City,UT,84152,1

### HINT

The syntax to select everything from a table in SQL is:

```sql
SELECT * FROM authors;
```

## 2.&nbsp;Select everything from the tables "titles", "titleauthor", "publishers" and "sales" (one table at a time). Look at the raw data and think about how these tables are related to each other.

In [ ]:
sales.head(1)

   stor_id ord_num             ord_date  qty payterms title_id
0     6380    6871  1994-09-14 00:00:00    5   Net 60   BU1032

In [ ]:
publishers.head(1)

   pub_id        pub_name    city state country
0     736  New Moon Books  Boston    MA     USA

In [ ]:
titleauthor.head(1)

         au_id title_id  au_ord  royaltyper
0  172-32-1176   PS3333       1         100

In [ ]:
titles.head(1)

,title_id,title,type,pub_id,price,advance,royalty,ytd_sales,notes,pubdate
0,BU1032,The Busy Executive's Database Guide,business,1389,19.99,5000.0,10,4095,An overview of available database systems with...,1991-06-12 00:00:00

In [ ]:
print(titles)
print(titleauthor)
print(publishers)
print(sales)

   title_id                                              title          type  \
0    BU1032                The Busy Executive's Database Guide      business
1    BU1111  Cooking with Computers: Surreptitious Balance ...      business
2    BU2075                    You Can Combat Computer Stress!      business
3    BU7832                      Straight Talk About Computers      business
4    MC2222                  Silicon Valley Gastronomic Treats      mod_cook
5    MC3021                              The Gourmet Microwave      mod_cook
6    MC3026                 The Psychology of Computer Cooking     UNDECIDED
7    PC1035                           But Is It User Friendly?  popular_comp
8    PC8888                          Secrets of Silicon Valley  popular_comp
9    PC9999                                      Net Etiquette  popular_comp
10   PS1372  Computer Phobic AND Non-Phobic Individuals: Be...    psychology
11   PS2091                                Is Anger the Enemy?    psychology
12   PS2106                                  Life Without Fear    psychology
13   PS3333      Prolonged Data Deprivation: Four Case Studies    psychology
14   PS7777                Emotional Security: A New Algorithm    psychology
15   TC3218  Onions, Leeks, and Garlic: Cooking Secrets of ...     trad_cook
16   TC4203          Fifty Years in Buckingham Palace Kitchens     trad_cook
17   TC7777                                     Sushi, Anyone?     trad_cook

    pub_id  price  advance  royalty  ytd_sales  \
0     1389  19.99   5000.0       10       4095
1     1389  11.95   5000.0       10       3876
2      736   2.99  10125.0       24      18722
3     1389  19.99   5000.0       10       4095
4      877  19.99      0.0       12       2032
5      877   2.99  15000.0       24      22246
6      877   0.00      0.0        0          0
7     1389  22.95   7000.0       16       8780
8     1389  20.00   8000.0       10       4095
9     1389   0.00      0.0        0          0
10     877  21.59   7000.0       10        375
11     736  10.95   2275.0       12       2045
12     736   7.00   6000.0       10        111
13     736  19.99   2000.0       10       4072
14     736   7.99   4000.0       10       3336
15     877  20.95   7000.0       10        375
16     877  11.95   4000.0       14      15096
17     877  14.99   8000.0       10       4095

                                                notes              pubdate
0   An overview of available database systems with...  1991-06-12 00:00:00
1   Helpful hints on how to use your electronic re...  1991-06-09 00:00:00
2   The latest medical and psychological technique...  1991-06-30 00:00:00
3   Annotated analysis of what computers can do fo...  1991-06-22 00:00:00
4   Favorite recipes for quick, easy, and elegant ...  1991-06-09 00:00:00
5   Traditional French gourmet recipes adapted for...  1991-06-18 00:00:00
6                                                 NaN  2014-11-07 10:39:37
7   A survey of software for the naive user, focus...  1991-06-30 00:00:00
8   Muckraking reporting on the world's largest co...  1994-06-12 00:00:00
9              A must-read for computer conferencing.  2014-11-07 10:39:37
10  A must for the specialist, this book examines ...  1991-10-21 00:00:00
11  Carefully researched study of the effects of s...  1991-06-15 00:00:00
12  New exercise, meditation, and nutritional tech...  1991-10-05 00:00:00
13  What happens when the data runs dry?  Searchin...  1991-06-12 00:00:00
14  Protecting yourself and your loved ones from u...  1991-06-12 00:00:00
15  Profusely illustrated in color, this makes a w...  1991-10-21 00:00:00
16  More anecdotes from the Queen's favorite cook ...  1991-06-12 00:00:00
17  Detailed instructions on how to make authentic...  1991-06-12 00:00:00
          au_id title_id  au_ord  royaltyper
0   172-32-1176   PS3333       1         100
1   213-46-8915   BU1032       2          40
2   213-46-8915   BU2075       1         100
3   238-95-7766   PC1035       1         100
4   267-41-2394   BU1111       2          40
5   267-41-2394   TC7777       2          30
6   274-80-9391   BU7832       1         100
7   409-56-7008   BU1032       1          60
8   427-17-2319   PC8888       1          50
9   472-27-2349   TC7777       3          30
10  486-29-1786   PC9999       1         100
11  486-29-1786   PS7777       1         100
12  648-92-1872   TC4203       1         100
13  672-71-3249   TC7777       1          40
14  712-45-1867   MC2222       1         100
15  722-51-5454   MC3021       1          75
16  724-80-9391   BU1111       1          60
17  724-80-9391   PS1372       2          25
18  756-30-7391   PS1372       1          75
19  807-91-6654   TC3218       1         100
20  846-92-7186   PC8888       2          50
21  899-46-2035   MC3021       2          25
22  899-46-2035   PS2091       2          50
23  998-72-3567   PS2091       1          50
24  998-72-3567   PS2106       1         100
   pub_id               pub_name        city state  country
0     736         New Moon Books      Boston    MA      USA
1     877       Binnet & Hardley  Washington    DC      USA
2    1389   Algodata Infosystems    Berkeley    CA      USA
3    1622  Five Lakes Publishing     Chicago    IL      USA
4    1756      Ramona Publishers      Dallas    TX      USA
5    9901                  GGG&G     Mnchen   NaN  Germany
6    9952         Scootney Books    New York    NY      USA
7    9999     Lucerne Publishing       Paris   NaN   France
    stor_id   ord_num             ord_date  qty    payterms title_id
0      6380      6871  1994-09-14 00:00:00    5      Net 60   BU1032
1      6380      722a  1994-09-13 00:00:00    3      Net 60   PS2091
2      7066     A2976  1993-05-24 00:00:00   50      Net 30   PC8888
3      7066  QA7442.3  1994-09-13 00:00:00   75  ON invoice   PS2091
4      7067     D4482  1994-09-14 00:00:00   10      Net 60   PS2091
5      7067     P2121  1992-06-15 00:00:00   40      Net 30   TC3218
6      7067     P2121  1992-06-15 00:00:00   20      Net 30   TC4203
7      7067     P2121  1992-06-15 00:00:00   20      Net 30   TC7777
8      7131   N914008  1994-09-14 00:00:00   20      Net 30   PS2091
9      7131   N914014  1994-09-14 00:00:00   25      Net 30   MC3021
10     7131    P3087a  1993-05-29 00:00:00   20      Net 60   PS1372
11     7131    P3087a  1993-05-29 00:00:00   25      Net 60   PS2106
12     7131    P3087a  1993-05-29 00:00:00   15      Net 60   PS3333
13     7131    P3087a  1993-05-29 00:00:00   25      Net 60   PS7777
14     7896    QQ2299  1993-10-28 00:00:00   15      Net 60   BU7832
15     7896     TQ456  1993-12-12 00:00:00   10      Net 60   MC2222
16     7896      X999  1993-02-21 00:00:00   35  ON invoice   BU2075
17     8042  423LL922  1994-09-14 00:00:00   15  ON invoice   MC3021
18     8042  423LL930  1994-09-14 00:00:00   10  ON invoice   BU1032
19     8042      P723  1993-03-11 00:00:00   25      Net 30   BU1111
20     8042   QA879.1  1993-05-22 00:00:00   30      Net 30   PC1035

### HINT

The syntax to select everything from a table in SQL is:

```sql
SELECT * FROM titles;

SELECT * FROM titleauthor;

SELECT * FROM publishers;

SELECT * FROM sales;
```

## 3.&nbsp;Select the authors first and last name

In [ ]:
authors[['au_lname', 'au_fname']]

          au_lname     au_fname
0            White      Johnson
1            Green     Marjorie
2           Carson       Cheryl
3          O'Leary      Michael
4         Straight         Dean
5            Smith      Meander
6           Bennet      Abraham
7             Dull          Ann
8       Gringlesby         Burt
9         Locksley     Charlene
10          Greene  Morningstar
11  Blotchet-Halls     Reginald
12        Yokomoto        Akiko
13    del Castillo        Innes
14        DeFrance       Michel
15        Stringer         Dirk
16      MacFeather      Stearns
17          Karsen        Livia
18        Panteley       Sylvia
19          Hunter       Sheryl
20        McBadden      Heather
21          Ringer         Anne
22          Ringer       Albert

### HINT

The syntax to select everything from a table in SQL is:

```sql
SELECT
    au_fname, au_lname
FROM
    authors
```

## 4.&nbsp;Select the publisher names

In [ ]:
publishers['pub_name'].head(2)

0      New Moon Books
1    Binnet & Hardley
Name: pub_name, dtype: object

### HINT

The syntax to select everything from a table in SQL is:

```sql
SELECT
    pub_name
FROM
    publishers;
```

## 5.&nbsp;Select the title, price and year-to-date sales of all titles

In [ ]:
titles[['title', 'price', 'ytd_sales']]

                                                title  price  ytd_sales
0                 The Busy Executive's Database Guide  19.99       4095
1   Cooking with Computers: Surreptitious Balance ...  11.95       3876
2                     You Can Combat Computer Stress!   2.99      18722
3                       Straight Talk About Computers  19.99       4095
4                   Silicon Valley Gastronomic Treats  19.99       2032
5                               The Gourmet Microwave   2.99      22246
6                  The Psychology of Computer Cooking   0.00          0
7                            But Is It User Friendly?  22.95       8780
8                           Secrets of Silicon Valley  20.00       4095
9                                       Net Etiquette   0.00          0
10  Computer Phobic AND Non-Phobic Individuals: Be...  21.59        375
11                                Is Anger the Enemy?  10.95       2045
12                                  Life Without Fear   7.00        111
13      Prolonged Data Deprivation: Four Case Studies  19.99       4072
14                Emotional Security: A New Algorithm   7.99       3336
15  Onions, Leeks, and Garlic: Cooking Secrets of ...  20.95        375
16          Fifty Years in Buckingham Palace Kitchens  11.95      15096
17                                     Sushi, Anyone?  14.99       4095

### HINT

The syntax to select everything from a table in SQL is:

```sql
SELECT
    title, price, ytd_sales
FROM
    titles;
```

## 6.&nbsp;Select all the authors first names, but display the column with the alias "first_name"

In [ ]:
authors.rename(columns={'au_fname':'first_name'})[['first_name']]

     first_name
0       Johnson
1      Marjorie
2        Cheryl
3       Michael
4          Dean
5       Meander
6       Abraham
7           Ann
8          Burt
9      Charlene
10  Morningstar
11     Reginald
12        Akiko
13        Innes
14       Michel
15         Dirk
16      Stearns
17        Livia
18       Sylvia
19       Sheryl
20      Heather
21         Anne
22       Albert

### HINT

The syntax to select everything from a table in SQL is:

```sql
SELECT
	au_fname AS first_name
FROM
	authors;
```

You can rename columns in pandas with the `rename` method, here is the link to the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

## 7.&nbsp;Select the job id and job description of all jobs, but display the columns with the names "id" and "description"

In [ ]:
(jobs.rename(columns={'job_id':'id', 'job_desc':'description'})
[['id','description']].set_index('id'))

                     description
id
1   New Hire - Job not specified
2        Chief Executive Officer
3    Business Operations Manager
4       Chief Financial Officier
5                      Publisher
6                Managing Editor
7              Marketing Manager
8       Public Relations Manager
9           Acquisitions Manager
10           Productions Manager
11            Operations Manager
12                        Editor
13          Sales Representative
14                      Designer

### HINT

```sql
SELECT
	job_id AS id,
	job_desc AS description
FROM
	jobs;
```

You can rename columns in pandas with the `rename` method, here is the link to the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html).

## 8.&nbsp;Select all unique last names of authors (the same last name cannot appear more than once)

In [ ]:
authors['au_lname'].unique()

array(['White', 'Green', 'Carson', "O'Leary", 'Straight', 'Smith',
       'Bennet', 'Dull', 'Gringlesby', 'Locksley', 'Greene',
       'Blotchet-Halls', 'Yokomoto', 'del Castillo', 'DeFrance',
       'Stringer', 'MacFeather', 'Karsen', 'Panteley', 'Hunter',
       'McBadden', 'Ringer'], dtype=object)

### HINT

```sql
SELECT
	DISTINCT au_lname
FROM
	authors;
```

## 9.&nbsp;Select all unique title id's that were involved in a sale

In [ ]:
#using drop_duplicates
sales.drop_duplicates("title_id")["title_id"]

0     BU1032
1     PS2091
2     PC8888
5     TC3218
6     TC4203
7     TC7777
9     MC3021
10    PS1372
11    PS2106
12    PS3333
13    PS7777
14    BU7832
15    MC2222
16    BU2075
19    BU1111
20    PC1035
Name: title_id, dtype: object

### HINT

```sql
SELECT
	DISTINCT title_id
FROM
	sales;
```